title: An Overview of the Divine Liturgy
remote_theme: jekyll/minima
github_username: ChThH
minima:
  skin: solarized-dark
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
header_pages: none
